// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiConsoleApp.Migrations
{
    [DbContext(typeof(SahaContext))]
    [Migration("20250711061618_LatLongState")]
    partial class LatLongState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kuyu", b =>
                {
                    b.Property<int>("KuyuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KuyuId"));

                    b.Property<int?>("SahaId")
                        .HasColumnType("int");

                    b.Property<string>("kuyuAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KuyuId");

                    b.HasIndex("SahaId");

                    b.ToTable("Kuyular");
                });

            modelBuilder.Entity("Saha", b =>
                {
                    b.Property<int>("SahaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SahaId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("sahaAdı")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SahaId");

                    b.ToTable("Sahalar");
                });

            modelBuilder.Entity("Wellbore", b =>
                {
                    b.Property<int>("WellboreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WellboreId"));

                    b.Property<int>("KuyuId")
                        .HasColumnType("int");

                    b.Property<string>("wellboreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WellboreId");

                    b.HasIndex("KuyuId");

                    b.ToTable("Wellbores");
                });

            modelBuilder.Entity("Kuyu", b =>
                {
                    b.HasOne("Saha", "Saha")
                        .WithMany("kuyuList")
                        .HasForeignKey("SahaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Saha");
                });

            modelBuilder.Entity("Wellbore", b =>
                {
                    b.HasOne("Kuyu", "Kuyu")
                        .WithMany("wellbores")
                        .HasForeignKey("KuyuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kuyu");
                });

            modelBuilder.Entity("Kuyu", b =>
                {
                    b.Navigation("wellbores");
                });

            modelBuilder.Entity("Saha", b =>
                {
                    b.Navigation("kuyuList");
                });
#pragma warning restore 612, 618
        }
    }
}
